class GenomeCli < Formula
  desc "Genomic data (array exports, WGS VCF, FASTQ), encrypted at rest"
  homepage "https://gitlab.com/davidawad/genome-cli"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/davidawad/genome-cli/releases/download/v0.2.0/genome-v0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "a8b71a620d2790f291f2e74bcf922a58b09b6d3c1cc78718e99ca2b2d0d571c7"
    end
    on_intel do
      url "https://github.com/davidawad/genome-cli/releases/download/v0.2.0/genome-v0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "6018da96e85fb40e53a68494a94808707354f2ba1c4eb77bbdc481fcdf3a7e45"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/davidawad/genome-cli/releases/download/v0.2.0/genome-v0.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "c1a08754646b20f60cf6f3fcd46af81d7b0f8c7500eb3c2c875635ccfba8c3d4"
    end
    on_intel do
      url "https://github.com/davidawad/genome-cli/releases/download/v0.2.0/genome-v0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a8f548361cc4dd8feaa94cf40e3ef27e3f1a092486fdd82ef81ae47b671f7573"
    end
  end

  # Prebuilt release binaries: fsqlite 0.4 needs nightly Rust on x86_64,
  # which Homebrew does not ship, so building from source is left to `cargo`.
  def install
    bin.install "genome"
    generate_completions_from_executable(bin/"genome", "completions")
    system bin/"genome", "man", "--dir", man1
  end

  def caveats
    <<~EOS
      Data is encrypted at rest; the key lives in the OS keychain by default.
      The FASTQ -> VCF pipeline (`genome pipeline`) needs:
        brew install minimap2 samtools bcftools
    EOS
  end

  test do
    (testpath/"kit.txt").write <<~EOS
      # This data file generated by 23andMe at: Thu Jan 01 00:00:00 2026
      # We are using reference human assembly build 37 (also known as Annotation Release 104).
      # rsid\tchromosome\tposition\tgenotype
      rs429358\t19\t45411941\tTC
      rs7412\t19\t45412079\tCC
    EOS
    ENV["GENOME_DATA_DIR"] = testpath/"data"
    ENV["GENOME_CACHE_DIR"] = testpath/"cache"
    ENV["GENOME_KEY"] = "brew-test-passphrase"
    ENV["GENOME_OFFLINE"] = "1"
    system bin/"genome", "import", testpath/"kit.txt", "--name", "t"
    assert_match "\"schema\": \"genome/v1\"",
                 shell_output("#{bin}/genome lookup t --rsid rs429358 --format json")
  end
end
