class GenomeCli < Formula
  desc "Genomic data (array exports, WGS VCF, FASTQ), encrypted at rest"
  homepage "https://gitlab.com/davidawad/genome-cli"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/davidawad/genome-cli/releases/download/v0.3.0/genome-v0.3.0-aarch64-apple-darwin.tar.gz"
      sha256 "d83f1804ecebcf296dc36713faef496a5dfe10a65aece7e7fdb135782639c438"
    end
    on_intel do
      url "https://github.com/davidawad/genome-cli/releases/download/v0.3.0/genome-v0.3.0-x86_64-apple-darwin.tar.gz"
      sha256 "8aa330b6908b55b7283739ba1efb30cc915ea3497d2de2566813111f35271e92"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/davidawad/genome-cli/releases/download/v0.3.0/genome-v0.3.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "2063269e98668df5967e00e181a4e4b95624e6350fd242f3bbe7d38d92b2576a"
    end
    on_intel do
      url "https://github.com/davidawad/genome-cli/releases/download/v0.3.0/genome-v0.3.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "755dc727f76755a5b7fac3d088d4ac6059e3be89dcf4143aa0ef7823ca2f3b81"
    end
  end

  # Prebuilt release binaries: fsqlite 0.4 needs nightly Rust on x86_64,
  # which Homebrew does not ship, so building from source is left to `cargo`.
  def install
    bin.install "genome"
    generate_completions_from_executable(bin/"genome", "completions")
    system bin/"genome", "man", "--dir", man1
  end

  def caveats
    <<~EOS
      Data is encrypted at rest with your SSH key (~/.ssh/id_ed25519) by default; see `genome key status`.
      The FASTQ -> VCF pipeline (`genome pipeline`) needs:
        brew install minimap2 samtools bcftools
    EOS
  end

  test do
    (testpath/"kit.txt").write <<~EOS
      # This data file generated by 23andMe at: Thu Jan 01 00:00:00 2026
      # We are using reference human assembly build 37 (also known as Annotation Release 104).
      # rsid\tchromosome\tposition\tgenotype
      rs429358\t19\t45411941\tTC
      rs7412\t19\t45412079\tCC
    EOS
    ENV["GENOME_DATA_DIR"] = testpath/"data"
    ENV["GENOME_CACHE_DIR"] = testpath/"cache"
    ENV["GENOME_KEY"] = "brew-test-passphrase"
    ENV["GENOME_OFFLINE"] = "1"
    system bin/"genome", "import", testpath/"kit.txt", "--name", "t"
    assert_match "\"schema\": \"genome/v1\"",
                 shell_output("#{bin}/genome lookup t --rsid rs429358 --format json")
  end
end
