class GenomeCli < Formula
  desc "Genomic data (array exports, WGS VCF, FASTQ), encrypted at rest"
  homepage "https://github.com/davidawad/genome-cli"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/davidawad/genome-cli/releases/download/v0.3.1/genome-v0.3.1-aarch64-apple-darwin.tar.gz"
      sha256 "0478a863ed2ee240a1f0dec0b29a97eb7892d1a65875210bc3b2edaa22d53ff2"
    end
    on_intel do
      url "https://github.com/davidawad/genome-cli/releases/download/v0.3.1/genome-v0.3.1-x86_64-apple-darwin.tar.gz"
      sha256 "8b557d6857554e697f93eb1ec4e3a4c889c9c4f3b7b50dd3de5f01adb25e98e7"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/davidawad/genome-cli/releases/download/v0.3.1/genome-v0.3.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "62d131bbd688a7daafd8aebadb8472e51d4d1cfae4ee015bd9ad64c844cc01a7"
    end
    on_intel do
      url "https://github.com/davidawad/genome-cli/releases/download/v0.3.1/genome-v0.3.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "4eba2e9d7bbf9b80a78fd88b06dcec2bcd7ae1215879c4ad9a06d26baacc3286"
    end
  end

  # Prebuilt release binaries: fsqlite 0.4 needs nightly Rust on x86_64,
  # which Homebrew does not ship, so building from source is left to `cargo`.
  def install
    bin.install "genome"
    generate_completions_from_executable(bin/"genome", "completions")
    system bin/"genome", "man", "--dir", man1
  end

  def caveats
    <<~EOS
      Data is encrypted at rest with your SSH key (~/.ssh/id_ed25519) by default; see `genome key status`.
      The FASTQ -> VCF pipeline (`genome pipeline`) needs:
        brew install minimap2 samtools bcftools
    EOS
  end

  test do
    (testpath/"kit.txt").write <<~EOS
      # This data file generated by 23andMe at: Thu Jan 01 00:00:00 2026
      # We are using reference human assembly build 37 (also known as Annotation Release 104).
      # rsid\tchromosome\tposition\tgenotype
      rs429358\t19\t45411941\tTC
      rs7412\t19\t45412079\tCC
    EOS
    ENV["GENOME_DATA_DIR"] = testpath/"data"
    ENV["GENOME_CACHE_DIR"] = testpath/"cache"
    ENV["GENOME_KEY"] = "brew-test-passphrase"
    ENV["GENOME_OFFLINE"] = "1"
    system bin/"genome", "import", testpath/"kit.txt", "--name", "t"
    assert_match "\"schema\": \"genome/v1\"",
                 shell_output("#{bin}/genome lookup t --rsid rs429358 --format json")
  end
end
